name: carting
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  easy_localization: ^3.0.7
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  flutter_spinkit: ^5.2.1
  dotted_border: ^2.1.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/anims/
