name: carting
description: "A new Flutter project."

publish_to: "none"

version: 1.0.15+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  device_info_plus: ^11.5.0
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  flutter_spinkit: ^5.2.2
  dotted_border: ^3.1.0
  keyboard_dismisser: ^3.0.0
  image_picker: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.1
  intl: ^0.20.2
  get_it: ^8.2.0
  dio: ^5.9.0
  logger: ^2.6.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  formz: ^0.8.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  image: ^4.5.4
  yandex_mapkit: ^4.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0
  http: ^1.5.0
  flex_dropdown: ^0.2.0
  animated_rating_bar: ^0.0.8
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  sms_autofill: ^2.4.1
  centrifuge: ^0.16.0
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.11.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/documents/
    - assets/fonts/Lufga-Medium.ttf
    - assets/fonts/Lufga-Regular.ttf

  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/Lufga-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lufga-Medium.ttf
          weight: 500
